volumes:
  pg_data:
  static:
  media:
networks:
  django-network-fg:
    driver: bridge
services:
  db:
    image: postgres:13.10
    env_file: .env
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: mysecretpassword
    networks:
      - django-network-fg
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: krohalevaa/foodgram_back
    env_file: .env
    networks:
      - django-network-fg
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: krohalevaa/foodgram_front
    env_file: .env
    networks:
      - django-network-fg
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: krohalevaa/foodgram_infra
    env_file: .env
    networks:
      - django-network-fg
    ports:
      - "8000:80"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/app/collected_static/
      - media:/app/media
