# Generated by Django 5.1.5 on 2025-02-03 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='measurement_unit',
            new_name='unit',
        ),
    ]
