# Generated by Django 5.1.5 on 2025-02-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_measurement_unit_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет в HEX'),
        ),
    ]
