# Generated by Django 5.1.5 on 2025-02-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания рецепта'),
        ),
    ]
